batchdump:
	( \
		source env/bin/activate; \
		python agents_simulator.py dump > simulated.batchdump; \
	)

simulation:
	( \
		source env/bin/activate; \
		python agents_simulator.py; \
	)

test:
	( \
		source env/bin/activate; \
		python test.py; \
	)
